---
- hosts: ubuntu
  tasks:
    - name: cont
      community.general.docker_container:
        name: ubuntu-container
        image: ubuntu:14.04
        command: sleep infinity

- hosts: webserver
  tasks:
    - name: nginx
      community.general.docker_container:
        name: ngix-server
        image: nginx:latest
        state: started
        ports:
          - 8080:80
